# Generated by Django 4.1.3 on 2022-12-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.ManyToManyField(related_name='Fkooditem', to='customer.category')),
            ],
        ),
        migrations.CreateModel(
            name='restraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('Food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.food_item')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.area')),
                ('category', models.ManyToManyField(related_name='rkestraunt', to='customer.category')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ManyToManyField(related_name='ckity', to='customer.category')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='category',
            field=models.ManyToManyField(related_name='akrea', to='customer.category'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.city'),
        ),
    ]
