# Generated by Django 4.1.3 on 2022-12-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='restraunt',
            old_name='area',
            new_name='Area',
        ),
        migrations.RemoveField(
            model_name='area',
            name='category',
        ),
        migrations.RemoveField(
            model_name='city',
            name='category',
        ),
        migrations.RemoveField(
            model_name='food_item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
